import Head from 'next/head'
import Image from 'next/image'
import PostsComponent from '../components/posts/posts.component'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import HeaderComponent from '../components/header/header.component'
import FooterComponent from '../components/footer/footer.component'


const queryClient = new QueryClient();

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   
      <HeaderComponent></HeaderComponent>
      <main>
        <QueryClientProvider client={queryClient}>
          <PostsComponent></PostsComponent>
        </QueryClientProvider>
      </main>
      <FooterComponent></FooterComponent>
    </div>
  )
}
