import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import postsPresenter from "../components/posts/posts.presenter";

export async function getServerSideProps(context) {

    const data = await postsPresenter.fetchPosts();

    return {
      props: {
        message: 'Test test test',
        data: data
      }, // will be passed to the page component as props
    }
  }

function Posts(props) {
    return ( <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main >
          <Link href="/">
            <a>Home</a>
          </Link>                 
          {props.message}

          {JSON.stringify(props.data)}
        </main>
  
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div> );
}

export default Posts;