import Head from 'next/head'
import Image from 'next/image'
import FooterComponent from '../components/footer/footer.component';
import HeaderComponent from '../components/header/header.component';
import postsPresenter from "../components/posts/posts.presenter";
import PostsListerComponent from '../components/posts/posts-lister.component';

export async function getServerSideProps(context) {

    const data = await postsPresenter.fetchPosts();
    console.log(data);
    return {
      props: {
        message: 'A test message!',
        data: data
      }, // will be passed to the page component as props
    }
  }

function Posts(props) {
    return ( <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HeaderComponent></HeaderComponent>  
        <main >               
          Message: {props.message}   
          <PostsListerComponent posts={props.data}></PostsListerComponent>       
        </main>  
        <FooterComponent></FooterComponent>
      </div> );
}

export default Posts;